### ISSUE TITLE
lunarvim + ben's vimtex setup

### ISSUE THREAD

**Issue by tjallemaal** [benbrastmckie/.config#102]
This is not an issue.

I've been using your config on MacOS for doing latex stuff and more generally anything editing related for about 2 years now.
It was the perfect start for vim in general :)
I tweaked some things, sort of `forked` it if you will.

Now I have Arch on a new computer and have this dilemma: 
I could try to put my old setup in there or try lunarvim first, as I'm eager to go deeper into coding stuff.
I know you were in the process of  exploring `lunarvim` as well, or possibly integrating a ` tex` setup? How is that going?

I'm not quite sure how to approach this now.

Sorry for clogging up your Issues section ( this is more of a rec/ discussion thing ..)

Thanks again! Writing tex your way is a breeze.

**Comment by benbrastmckie** [comment]
Glad to hear the config is working nicely for you! Regarding your question, I started off with what has now become Lunar Vim, though in looking at what Lunar Vim (and other similar configs) have become, I'm not sure I'd recommend it. My impression is that they are both very well developed, but as a result, hard to tinker on if that's something you are looking to do. It's a bit like buying a BMW. Great car, but don't try to change it too much.

Anyhow, that's just my impression. For myself, I've been starting to pair down plugins a little bit, and hope to someday find someone who has skills beyond mine to help me really polish the config. But for the time being, it works great and I'm happy letting it be as it is, focusing on using it instead. But if you are looking for a new project, I'm sure that you'd learn a ton by taking Lunar Vim apart and getting it set up for your needs. If you do end up doing so, please link your config below. I'd love to take a look.

Cheers!

**Comment by benbrastmckie** [comment]
I'm going to close this issue, moving matters here: https://github.com/benbrastmckie/.config/discussions/103#discussion-5402654

**Comment by tjallemaal** [comment]
Thanks for your feedback! 
Yeah I'm curious to integrate vimtex into lunarvim, but right now I'm not knowledgable enough I don't even know if that would make sense ...
I'm left with one question for now: If you don't really use lunar anymore, how do you compile code other than tex? (if that's a thing for you at all)

**Comment by tjallemaal** [comment]
oh, I see there's quite some talk about this on @machine's discord about that combo!  ... and down the rabbit hole :3

**Comment by benbrastmckie** [comment]
Currently I don't compile code, though that is definitely the direction I'm going in. I would be very interested to integrate python and perhaps other languages into the config. I'm curious what you find down the rabbit hole, and if switching to Lunar Vim seems like a good choice. Alternatively, I wonder what can be gleaned from Lunar Vim, or other setups, and if just those pieces can be woven into the LaTeX config with greater ease.

**Comment by tjallemaal** [comment]
On discord, a lunar vim dev told me everything should go smooth (putting vimtex to the lunarvim mix) 
apparently there was a bug which got fixed, but I don't if that was the reason exactly why you got discouraged. cheers!

**Comment by benbrastmckie** [comment]
The bug was part of it, but also wanted to keep things light to reduce the risk of things breaking after updates. But you are definitely inspiring me to reconsider and curious to see what you come up with :)
