### ISSUE TITLE
using any packages causes a compilation error 

### ISSUE THREAD

**Issue by Shawarm0** [benbrastmckie/.config#104]
Hello, I'm very new to neovim as an IDE and am trying my best to learn how to customise it for my needs. Currently overleaf is the application i spend most of my time on and neovim seemed incredibly appealing in increasing my work flow. 

I have been able to get everything downloaded with a few issues i can't seem to work around.  Whenever compiling a document with Zathura as my PDF viewer, it seems to return a black screen 

![image](https://github.com/benbrastmckie/.config/assets/130526452/7dd27fb0-10e8-4635-beeb-d8acc3b57ade)

i tried changing this to general and i it seemed to compile without any issues. Obviously i would like for zathura to work but it is not the end of the world.

My second issue is with packages. When trying to compile a blank document just to test the compilation everything seemed to work fine. It updated as i wrote the file. However i get a compilation failed error everytime packages are imported. 

![image](https://github.com/benbrastmckie/.config/assets/130526452/5d26fc28-ab64-4e84-9237-a3d2fdb2793f)
![image](https://github.com/benbrastmckie/.config/assets/130526452/6ce5d113-42e3-44b5-9d9a-34ff6fc2f309)

Any help would be appreciated.

**Comment by tjallemaal** [comment]
You on linux or MacOS?
As far I as I remember, skim is recommended for MacOS.

**Comment by Shawarm0** [comment]
> You on linux or MacOS?
> As far I as I remember, skim is recommended for MacOS.
> 
Sorry forgot to mention I'm using Fedora workstation 38

**Comment by benbrastmckie** [comment]
Sorry for my delay... I've been away from my computer. What does your error report look like? You can generate it with `<space>ar`. 

Can you get Zathura to open any pdf on your computer? If not, there is an issue with Zathura in Fedora, and I would suggest searching 'Zathura Fedora' to troubleshoot the issue.
