### ISSUE TITLE
nvim error in init.lua

### ISSUE THREAD

**Issue by ammukuttu** [benbrastmckie/.config#109]
This error comes up on both Mac and Linux. Please advise how to revert to version 2 or put the fix for version 3. 

_You are trying to call the setup function of indent-blankline version 2, but you have version 3 instal
led.
Take a look at the GitHub wiki for instructions on how to migrate, or revert back to version 2._

**Comment by benbrastmckie** [comment]
Yep, very annoying... here is an easy fix. Go into `plugins.lua` and add the commit line as below:
```
  use { 
    "lukas-reineke/indent-blankline.nvim", 
    commit = "9637670896b68805430e2f72cf5d16be5b97a22a" 
    -- still need to merge to V3 to avoid this
  }
```
At some point I will merge to V3, but that will require more changes to the indentline.lua config file.

**Comment by ammukuttu** [comment]
unfortunately, it still persists. I get the same error

**Comment by benbrastmckie** [comment]
Did you update packer? You could try `:PackerClean` and `:PackerUpdate`.

**Comment by ammukuttu** [comment]
Thanks. Running those commands gave this errors:

```
packer.nvim] [ERROR 09:02:04] async.lua:20: Error in coroutine: vim/_editor.lua:0: nvim_exec2()../Users/jay
raghavan/.local/share/nvim/site/pack/packer/start/indent-blankline.nvim/plugin/indent_blankline.vim, line 31
: Vim(lua):E5108: Error executing lua [string ":lua"]:1: attempt to call field 'init' (a nil value)
stack traceback:
^I[string ":lua"]:1: in main chunk
^I[C]: in function 'resume'
^I.../site/pack/packer/start/packer.nvim/lua/packer/async.lua:12: in function <.../site/pack/packer/start/pa
cker.nvim/lua/packer/async.lua:11>

```
after hitting ENTER, this warning:

```
[packer.nvim] [WARN  09:03:44] display.lua:612: Potential breaking change in commit 13e415c of lukas-reineke
/indent-blankline.nvim
```

after packer finishes, in the popup dialog this message:

`Failed to update lukas-reineke/indent-blankline.nvim
`
After quitting nvim, restarting it gave no error! Voila!!

Is the initial error in async.lua expected? Out of abundance of caution, I reverted the plugins.lua change you recommended and did the same packer clean/update routines, and there were no errors reported out of async.lua

**Comment by benbrastmckie** [comment]
I don't think so. Sometimes to update a package you have to restart nvim. So I think you should be all good. At some point I will merge to V3 so as to avoid pinning that commit. How to do this is explained on the indent-blankline github but I haven't found the time.
