### ISSUE TITLE
screen split

### ISSUE THREAD

**Issue by LAffey26** [benbrastmckie/.config#130]
I want to know how you made the screen split into two parts when using nvim and a pdf file.

**Comment by benbrastmckie** [comment]
Just the way any two programs can split the screen in gnome (in this case it's neovim in the terminal and zathura pdf reader). I'm considering moving to a window manager at some point but gnome is good enough for now. I assume something similar is possible on macOS and windows.

**Comment by LAffey26** [comment]
Thanks, because I'm already tired of constantly moving desktop windows .
