### ISSUE TITLE
Nvim noob here, how do I put on a monokai theme?

### ISSUE THREAD

**Issue by sjitborre1** [benbrastmckie/.config#133]
title says it all. I want a monokai theme, I have tried a couple of things but always end up breaking the config.

**Comment by benbrastmckie** [comment]
I just pushed a [block](https://github.com/benbrastmckie/.config/blob/19307dd0a522253ec6fa995d4aed3d2b6cf0b66e/nvim/lua/neotex/plugins/colorscheme.lua#L26) which you can uncomment to try out. You will need to find the same file in your config, and comment out the first block for gruvbox. Then put the block linked above somewhere in that file. I didn't test it, so let me know if that works.

**Comment by sjitborre1** [comment]
Yes! Thanks, it works!
