### ISSUE TITLE
Git errors

### ISSUE THREAD

**Issue by ammukuttu** [benbrastmckie/.config#135]
After opening a saved session and then trying to commit the edits within nvim, I see error:

`Not in a git repository. Create a new repository?  (y/n)`

**Comment by ammukuttu** [comment]
This error was due to not opening nvim from the directory which has the source files to be committed. The saved session should match the directory/folder name where the .git folder for those files exist.

By deleting the session and then opening the file from source location as mentioned above, saving that as a session, no more  git errors

**Comment by benbrastmckie** [comment]
Thanks for documenting this! One other point worth mentioning is `space,a,u` will change the directory to buffer currently open which can be useful before saving a session in case you started from somewhere else.
