### ISSUE TITLE
neovim checkhealth errors and icons

### ISSUE THREAD

**Issue by jayraghavan** [benbrastmckie/.config#20]
neovim checkhealth displays a few errors and some warnings.

  - ERROR: nvr executable is not found, run `pip install neovim-remote` to install

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

also seeing some weird characters when nvim is started up

![Screen Shot 2020-06-18 at 9 18 54 AM](https://user-images.githubusercontent.com/39407962/85024930-bd4c2d00-b144-11ea-995a-8430ef07feed.png)

all assistance appreciated

**Comment by benbrastmckie** [comment]
Regarding the health warnings, I assume you followed the instructions recommended. Did that not solve the issue? For this first one, I would run `pip3 install neovim-remote`. Also, is there some reason you need Python 2 and Ruby? If not, I wouldn't worry about the warnings.

Regarding the missing characters, this can be solved by installing a nerdfont. I have included instructions in the Readme.md towards the bottom. Once you move the font I included in the repo to the correct location, you will need to set that font in the terminal preferences. Let me know if that takes care of things or if you face further difficulties.
