### ISSUE TITLE
change keymap in neovim

### ISSUE THREAD

**Issue by jayraghavan** [benbrastmckie/.config#21]
Changing the keymap seems to have no effect in neovim.

I use the iast.vim keymap, to type text that has diacritical marks. This keymap file is present in the keymap folder. In vim, typically you change the keymap 
:set keymap=iast

nvim takes the command and doesn't error out. However typing text following IAST conventions, for example -a should generate a with a bar over a does not happen.

Is this due to alacritty or neovim. This doesn't work on iterm2 too which leads me to believe it is due to something in neovim

Typing diacritical text is very important for my project. 

Note: vim works well and is able to change keymap and corresponding in text

**Comment by benbrastmckie** [comment]
Have you tried sourcing the iast.vim file by adding the following to init.vim:
```
source $HOME/.config/nvim/keys/which-key.vim
```
You will need to have moved iast.vim to ~/.config/nvim/keys.

**Comment by jayraghavan** [comment]
init.vim already sources this
`source $HOME/.config/nvim/keys/which-key.vim`
so change needed there. I moved the iast.vim to ~/.config/nvim/keys and didn't have any impact and therefore reverted.

I was though able to make it work! The problem seems to be speed of entry. The two key have to be entered in quick succession for the diacritic to show up. In my 7 years of editing this type of files in vim, I've never had this limitation. Is there a feature in feature in nvim to manage this. Now I've to be real quick to enter the two keys in succession. To verify if this is a function of the terminal, both alacritty and iterm2 show same behavior. Whereas, vim still works as expected, i.e. with no need to type two keys in fast succession to get the diacritic.

Typically keymap files are stored here
`/usr/local/share/nvim/runtime/keymap`

In the case of vim:
`/usr/local/share/vim/vim82/keymap`

**Comment by benbrastmckie** [comment]
Sorry I forgot to change 'which-key.vom' to 'iast.vim'. What I meant to ask is if you sourced iast.vim by including the following in init.vim:
```
source $HOME/.config/nvim/keys/iast.vim
```
Regarding the timing of keystrokes, I tried messing with the timing by including the following for another issue I was having:
```
set timeout timeoutlen=500 ttimeoutlen=0 
```
I didn't like the delay it created, and found another work around using keybindings.

**Comment by jayraghavan** [comment]
I didn't have to source the iast.vim as I would like to set the keymap only for certain documents. Usually I set a keybinding to toggle the keymap setting.

The `set timeout timeoutlen=300` worked. I tried different values and 300 seems to be the lowest that works at acceptable rate.
