### ISSUE TITLE
Connecting file.bib to coc autocomplete.

### ISSUE THREAD

**Issue by VolkovIlia** [benbrastmckie/.config#29]
Cant find any instructions or code for connecting bibtex file and custom trigger keys for coc. Can you add it to tutorial?

**Comment by benbrastmckie** [comment]
I will try to make a tutorial on those points soon, however, in the mean time you can consult these installation instructions which describe where to place your Zotero Library (or other bibtex file): http://www.benbrastmckie.com/tools#access

For customizing coc, see the coc-settings.json file in the .config/nvim folder, as well as coc.vim in .config/nvim/plug-config. There are also some related mappings for coc which I suspect is what you are asking about in mappings.vim in .config/nvim/keys. I've got it set to use `ctrl+j/k` to tab through coc, and `return` to select and `tab` to un-select (for instance in using snippets). See this tutorial for examples: https://www.youtube.com/watch?v=KGqrpnxoDxw&list=PLBYZ1xfnKeDToZ2XXbUGSC7BkorWdyNh3&index=2
