### ISSUE TITLE
alternative to FZF?

### ISSUE THREAD

**Issue by benbrastmckie** [benbrastmckie/.config#34]
Looks like there may be a better alternative to FZF.
Is it worth switching?

**Comment by benbrastmckie** [comment]
Telescope is perhaps better: https://www.youtube.com/watch?v=8SqFt5h2Lsg

**Comment by benbrastmckie** [comment]
Config walkthrough: https://m.youtube.com/watch?v=Ua8FkgTL-94

**Comment by kunzaatko** [comment]
Maybe you can look at this: https://github.com/liuchengxu/vim-clap . It is performant and with lots of things already built in. I feel it aligns with the feel of this project quite well.

**Comment by benbrastmckie** [comment]
Hey good shout! I'll take a closer look. It looks sort of like what coc is
giving me, but will have to watch some videos to see it in action to get a
better sense.

**Comment by benbrastmckie** [comment]
It seems that nvim-lsp etc will cover this functionality.
