### ISSUE TITLE
Character on line 47 .tmux.conf?

### ISSUE THREAD

**Issue by artemp84** [benbrastmckie/.config#56]
What is the font you are using to display the Unicode character on line 47 of .tmux.conf?
`set -g status-left '#[fg=yellow]#S ⧉ '`

![tmux](https://user-images.githubusercontent.com/8567154/107216046-d9267b00-6a14-11eb-9e61-c1f6d6714ade.png)

**Comment by benbrastmckie** [comment]
It's Roboto Mono which you can find [here](https://github.com/benbrastmckie/.config/tree/master/fonts/RobotoMono), though most of the [Nerd Fonts](https://github.com/reorx/nerd-fonts) will do.

You can find instructions in my README.md file.
