### ISSUE TITLE
Auto-pairs in insert mode

### ISSUE THREAD

**Issue by benbrastmckie** [benbrastmckie/.config#72]
"If I'm in Insert mode and I type a 'paired' symbol (like ' " { [ ( , etc.) in a document where this symbol already appears later on, it automatically jumps to that instance of the symbol. That is, it doesn't let me actually 'type' the symbol. I usually just have to yank/paste it from there. Do you have any idea what I should tweak to change this? I figure it has something to do with the auto-pair features/plugins, but I've tried disabling them and the problem still persists." (Eoin Carney)

**Comment by benbrastmckie** [comment]
Great question. This is something I've thought about, but unless I'm missing something, there is just a bit of a trade-off here. I (mostly) really like being able to move outside the closure of a pairing, however, there are times were this misfires. Instead of killing the feature, I've tried to get better at avoiding the misfires, and it has mostly gone away. The main trouble comes if I accidentally delete the closure of a paired symbol, and try to type it back in instead of hitting `u` for undo. This is an easy thing to unlearn. Other cases might be harder, where you really do mean to delete a bunch of text, and somehow this leaves incomplete parings. I haven't yet investigated, but wonder if this is one of the many things which tree-sitter can help with, generating code actions which can fix errors, etc. For the time being, I'm waiting before moving the config to lua, including the native lsp, telescope, and tree-sitter etc. Also, there are I think rewrites in lua of some of the vim-autopair and vim-sandwich plugins, but not sure if they will make the same trouble go away.

Anyhow, if you want the functionality to go away, which I'm not sure will be less annoying, you might check out [fly mode](https://github.com/jiangmiao/auto-pairs#fly-mode), though I only gave it a quick read, and didn't test anything. I was surprised that a general search did not bring up an immediate answer to your question, suggesting that people mostly deal with the problem by avoiding the misfire as described above. Anyhow, hope that helps!

Also, in case there are other issues that you are having, make sure to open separate issues for each so that the issues stay organised around single topics.

**Comment by loopdreams** [comment]
Hi! Thanks so much for the detailed reply! It helps a lot. It only occasionaly happens to me yes, but I was just curious in case I had set up something wrong. I understand totally now what is happening (the auto-jump to outside the pair) and it makes sense :) you're right, I've mostly avoided it automatically so it's not too much of an issue. I think the main case is when I'm retroactively adding in parenthesis, etc., but the best vim-like thing is probably to stick to using the surround feature (the shift-s you've set up). I do usually use that but sometimes slip back into old, less-efficient ways of manually inserting! Anyway, thanks so much again for the reply and the great videos.

**Comment by benbrastmckie** [comment]
I see, then yes, surround is the way forward. Of course everyone's got what works for them, but if I'm enclosing a bunch of stuff (i.e., more than a few words) in parentheses, or etc., I like to use `vt_` where the blank is replaced with the character I'm selecting up to, and similarly for `vf_`. Alternatively, I sometimes use `veee...` to select to the end of the next, next, next,... word. Once I've got my selection, I'll carry on with `shift+s` etc. Sometimes when the text object to be surrounded is really clear, I'll use `space+s,s_` where the text object replaces the blank, but I get a lot of misfires this way. More common is to use `space+s,c_*` to swap whatever the blank is replaced with for whatever the star is replaced with, where closing brackets should always be used rather than opening brackets unless you also want padding. Hope that helps!
