### ISSUE TITLE
Mapping conflict for Ctrl+n

### ISSUE THREAD

**Issue by Alekssavin** [benbrastmckie/.config#74]
Hi.
I use your neovim configuration.
I saw in your video that you assigned selection of next occurrences of the word to `Ctrl + n` key combination.
When I try to use it in a text file I get an error from neovim:
```
VM has started with warnings. :VMDebug for more info
:VMDebug
b1: Overwritten imap: <CR> (I Return)  ->  <SID>AutoPairsOldCRWrapper73<SID>AutoPairsReturn
b1: Overwritten imap: <BS> (I BS)  ->  <C-R>=AutoPairsDelete()<CR>
```

I assume there is a mapping conflict. Can you please fix it?

**Comment by benbrastmckie** [comment]
Hey there, sorry to hear that you're having a conflict. I would try running the following command:

```
   :verbose nmap <C-n>
```

This should print our all places where the binding is set. If there are conflicts, you should be able to track them down and make any necessary changes. If there are no conflicts (i.e., it only lists one place the binding is set) you could try commenting out the line where the binding is set and running the command above again after reloading the config (you can quite and exit, or use `space+_` where the `_` is to be replaced either with `r` or `R` depending on when you pulled down my config, as I've continued to make improvements).

If none of that works, you could also try pulling down a more recent version of my config by opening the terminal and running:

```
   cd ~/.config
   git remote -v
   git pull origin master
```

The second command above checks that you have the right Git hooks set up. If you do pull down the latest, and want to go back, you can make your life a bit easier by first creating a branch in Git called 'old' or whatever you like. To do this, run:

```
   nvim ~/.config/nvim/init.vim
```

Then hit `<space>gg` to open the LazyGit menu. Navigate to `Local Branches` with `l` and `h`, creating a new branch with `n`. After naming your branch, you should re-select the `master` branch with `j` and `k` in the `Local Branches` pane, hitting `<space>` to checkout `master`. You can then leave LazyGit with `<esc>`. Having created this branch, you can now go ahead and pull down recent commits from my config, and if you don't like the changes, easily hop back to the branch you just created by checking it out instead. As I do not experience the conflict you are getting, this should clear up your difficulties. With that said, any changes you have made to your config may create git merge conflicts which will take some sorting out. Anyhow, it's an option to consider.

**Comment by Alekssavin** [comment]
Thank you for your response.

I have the most recent version of your repo, which I just have forked for myself.

When I type
`:verbose nmap <C-n>`
I get:
`n  <C-N>         <Plug>(VM-Find-Under)utoload/plugged/vim-visual-multi/autoload/vm/maps.vim line 18
        Last set from ~/.config/nvim/autoload/plugged/vim-visual-multi/autoload/vm/maps.vim line 18`

There is strange piece of code where the message sends me to.

**Comment by benbrastmckie** [comment]
Can you send me the strange code?

**Comment by Alekssavin** [comment]
`fun! vm#maps#default() abort
    " At vim start, permanent mappings are generated and applied.
    call s:build_permanent_maps()
    for m in g:Vm.maps.permanent | exe m | endfor
endfun`

The line 18 is apparently the for loop.
Apparently this code is referenced in `:verbose nmap <C-n>` output.

**Comment by Alekssavin** [comment]
Should I wait for this issue to be resolved in your upcoming update of the config, when you deploy nvim-lsp?

**Comment by benbrastmckie** [comment]
I have to confess that I don't know what is going on here. From your original error it looks like a conflict with autopairs, though I don't have any such conflict despite also using autopairs. You might try posting on r/neovim or open an issue in the repos for either multicursor or autopairs. In any case, switching to nvim-lsp should not make any difference here.

For further troubleshooting, you could try commenting out the autopairs `plugins.vim`, reloading nvim, and running `:PlugClean`, and checking to see if you can get <C-n> working. Alternatively, you can mess around with different mappings in `multicursor.vim`, replacing <C-n> with something else. To avoid conflicts, I would first run `:verbose nmap X` where 'X' is replaced with your candidate mapping to see if it is free. You can also just run `:verbose nmap` to see all mappings in normal mode. Hope that helps!

**Comment by benbrastmckie** [comment]
I have ported my config to lua with nvim-lsp etc. Not sure if this helps with the problem that you were having. Hope you were able to sort it out. If not, feel free to reopen the issue.
