### ISSUE TITLE
TeX snippets do not work as expected.

### ISSUE THREAD

**Issue by Alekssavin** [benbrastmckie/.config#76]
Hi. Sorry for bombarding you with new issues today.

I have your latest config installed.
I was trying to use snippets the same way you do on the [video](https://www.youtube.com/watch?v=KGqrpnxoDxw&list=PLBYZ1xfnKeDToZ2XXbUGSC7BkorWdyNh3&index=2).
However, I don't get an option to choose opening and closing commands at once (i.e. \begin{document} \end{document}).
The only functionality I have is I can see the drop-down menu after starting typing a latex command and I can complete the command. I don't see the closing command appearing after.

**Comment by benbrastmckie** [comment]
No worries! This one I can't get to work either, and am glad to know about it. I'm not sure what I changed which has made that functionality go missing. I did some poking around, but can't easily fix it. Thanks for flagging the issue!

I was thinking about switching to nvim-lsp so as to trim down the config, hopefully making it even faster and simpler. I haven't gone through this yet, but perhaps this will sort out the issue by providing equivalent functionality. Not sure how soon I'll get to it, but hopefully in the next month or so.

**Comment by Alekssavin** [comment]
Ok. Will you update this config all together or will there be just minor fixes?
I look forward to test the new config.

**Comment by benbrastmckie** [comment]
Yeah, the plan was to do a major overhaul, and to create new and slightly more systematic videos to go along with the result. It's a bit of work, but hope to get to it in June. You can see some of what I've taken as inspiration by browsing the other issues that I've opened. Feel free to add other suggestions if you come across anything that looks like it would fit nicely in this project. Cheers!

**Comment by benbrastmckie** [comment]
I have ported my config to lua in case that is of interest to you. Hope that you were able to sort out you issues before. Feel free to reopen the issue if not.
