### ISSUE TITLE
.gitignore update

### ISSUE THREAD

**Issue by Alekssavin** [benbrastmckie/.config#77]
Would you consider changing your `.gitignore` file so `git` always includes only the needed config files and omits everything else? That may be easier for those who learn how to set up a scientific writing enviroment by pulling your config.

Your `.gitignore` file would look like this:
```
# exclude all files
*

# these files are not ignored
!.gitignore
!.Xmodmap
!.gitignore
!.xmodmap.desktop
!CheatSheet.md
!LearningGit.md
!NOTES.md
!README.md
!alacritty/alacritty.yml
!fonts/RobotoMono/Roboto Mono Bold Italic Nerd Font Complete Mono.ttf
!fonts/RobotoMono/Roboto Mono Bold Nerd Font Complete Mono.ttf
!fonts/RobotoMono/Roboto Mono Italic Nerd Font Complete Mono.ttf
!fonts/RobotoMono/Roboto Mono Light Italic Nerd Font Complete Mono.ttf
!fonts/RobotoMono/Roboto Mono Light Nerd Font Complete Mono.ttf
!fonts/RobotoMono/Roboto Mono Medium Italic Nerd Font Complete Mono.ttf
!fonts/RobotoMono/Roboto Mono Medium Nerd Font Complete Mono.ttf
!fonts/RobotoMono/Roboto Mono Nerd Font Complete Mono.ttf
!fonts/RobotoMono/Roboto Mono Thin Italic Nerd Font Complete Mono.ttf
!fonts/RobotoMono/Roboto Mono Thin Nerd Font Complete Mono.ttf
!latex/bst/Analysis.bst
!latex/bst/Phil_Review.bst
!lazygit/config.yml
!lazygit/state.yml
!nvim/coc-settings.json
!nvim/docs/script.md
!nvim/ftplugin/markdown.vim
!nvim/ftplugin/tex.vim
!nvim/general/settings.vim
!nvim/init.vim
!nvim/keys/functions.vim
!nvim/keys/mappings.vim
!nvim/keys/which-key.vim
!nvim/plug-config/autopairs.vim
!nvim/plug-config/coc.vim
!nvim/plug-config/deoplete.vim
!nvim/plug-config/floaterm.vim
!nvim/plug-config/fzf.vim
!nvim/plug-config/gitgutter.vim
!nvim/plug-config/goyo.vim
!nvim/plug-config/markdown-preview.vim
!nvim/plug-config/markdown.vim
!nvim/plug-config/multicursor.vim
!nvim/plug-config/nerdtree.vim
!nvim/plug-config/pandoc.vim
!nvim/plug-config/quickscope.vim
!nvim/plug-config/rnvimr.vim
!nvim/plug-config/signify.vim
!nvim/plug-config/sneak.vim
!nvim/plug-config/start-screen.vim
!nvim/plug-config/templates.vim
!nvim/plug-config/thesaurus.vim
!nvim/plug-config/ultisnips.vim
!nvim/plug-config/vbox.vim
!nvim/plug-config/vifmrc
!nvim/plug-config/vim-commentary.vim
!nvim/plug-config/vim-surruound.vim
!nvim/plug-config/vimtex.vim
!nvim/snips/tex.snippets
!nvim/templates/Glossary.tex
!nvim/templates/HandOut.tex
!nvim/templates/Letter.tex
!nvim/templates/MacPhilArticle.tex
!nvim/templates/MultipleAnswer.tex
!nvim/templates/NiceArticle.tex
!nvim/templates/PhilBeamer.tex
!nvim/templates/PhilPaper.tex
!nvim/templates/Root.tex
!nvim/templates/SubFile.tex
!nvim/templates/Subfiles/Chapters/Ch1/Ch1.tex
!nvim/templates/Subfiles/Chapters/Ch2/Ch2.tex
!nvim/templates/Subfiles/Root.tex
!nvim/templates/Thesis.tex
!nvim/templates/TikZArc.tex
!nvim/templates/TuftsSample.tex
!nvim/templates/WinPhilArticle.tex
!nvim/themes/airline.vim
!nvim/themes/gruvbox.vim
!nvim/themes/onedark.vim
!nvim/vim-plug/plugins.vim
!tmux/.tmux.conf
!vifm/vifmrc
!zathura/themes/DarkGuide.png
!zathura/themes/LightGuide.png
!zathura/themes/dracula-light
!zathura/themes/dracula-light.png
!zathura/themes/zathura-gruvbox-dark
!zathura/themes/zathura-gruvbox-light
!zathura/themes/zathura-solarized-dark
!zathura/themes/zathura-solarized-light
!zathura/zathurarc
```

**Comment by benbrastmckie** [comment]
I would do, however, I wanted to make such files available to others. For instance, some of the templates could be useful, at least to customise for oneself. There is also .tmux.conf, font files, and other files related to the config which I figure will be of use. But if you have forked the config, you can go through and delete whatever you don't want.

**Comment by Alekssavin** [comment]
> I would do, however, I wanted to make such files available to others. For instance, some of the templates could be useful, at least to customise for oneself. There is also .tmux.conf, font files, and other files related to the config which I figure will be of use. But if you have forked the config, you can go through and delete whatever you don't want.

And such templates and configs are not omitted in the `.gitignore` I posted just above.

**Comment by benbrastmckie** [comment]
Oh true, I should unignore those templates. What trouble are the extraneous files causing for you? Is it that you want to be able to pull down updates without continuing to replace these extra files you don't want?

**Comment by benbrastmckie** [comment]
Hey just returning to this. Would it help to put all the extras in a folder for extras which people can ignore if they are not needed?

**Comment by Alekssavin** [comment]
I think people can add files they want to ignore in the `.gitignore` file themselves.
I think you should set your `.gitignore` so that everything but your config files are omitted. In this way only your config files are pushed and pulled when needed, and all the other files in a person's who has pulled your config `~/.config/` folder are omitted.
