### ISSUE TITLE
Using with zsh

### ISSUE THREAD

**Issue by Martin-2019** [benbrastmckie/.config#78]
The question is: how should the configuration steps proceed for the case in which I do not intend to use the Fish shell - I work in OS X with ZSH.

**Comment by benbrastmckie** [comment]
Which configuration steps? Using fish is completely optional, so nothing should turn on it. What problem are you having?

**Comment by Martin-2019** [comment]
I understood that Fish should be enabled for proper operation - as I understand it, step: ... Replace /usr/bin/fish with the location of fish should be replaced with zsh pointing.

I am a newbie, hence the question.

**Comment by benbrastmckie** [comment]
That step is in an optional section. Replacing `fish` with `zsh` will also work. But this only changes how you interact with the terminal, not vim. Hence why it is optional.

**Comment by Martin-2019** [comment]
Thank you very helpful information for a newbie!
