### ISSUE TITLE
vimlatex won't compile

### ISSUE THREAD

**Issue by Halem998** [benbrastmckie/.config#79]
i'm trying to switch from Texstudio to your incredible workflow :)

but I can't compile it properly ...

`config`:
https://gist.github.com/tjallemaal/bb855e9d0261a0af61c2377e74dc6b1d

I'm on a Mac, so I installed skim.
Also, i've installed Kitty instead of Alacritty, hope this does not make the difference after all...

**Comment by tjallemaal** [comment]
https://gist.github.com/tjallemaal/4f50ad671c74d09dfa1b6b7e5f52daa5

**Comment by benbrastmckie** [comment]
I would definitely begin by following the advice given in Checkhealth. In particular, you should get `nvr` working:

https://github.com/mhinz/neovim-remote

Seems like you're on the right track. Just keep going!

**Comment by tjallemaal** [comment]
just so i understand: was `nvr` not in the plugin bundle? should i put it there or can i just install it separately now?

also in line 2 of my `config file` it says:
`" http://manpages.ubuntu.com/manpages/trusty/man5/zathurarc.5.html`
given i use skim , shouldn't i change that line? if so, what should i place there?
