### ISSUE TITLE
coc-explorer, again 

### ISSUE THREAD

**Issue by tjallemaal** [benbrastmckie/.config#82]
I'm sorry to bother, as I believe this is not specific to your latex setup:

I am trying to switch from coc-explorer to ranger.

One problem: 
when I uninstall the coc-explorer, nvim reinstalls the explorer upon restart. How do I avoid this?

PS: (Unrelated) I'm eager to install LunarVim for coding, could there be a conflict with your latex-setup?

**Comment by tjallemaal** [comment]
I found this in the `plugins.vim` file
but weirdly Coc-Explorer isn't there... it got reinstalled though!
Or is it the wrong spot?

" File Explorer
    Plug 'ryanoasis/vim-devicons' "adds icons to coc-explorer
    " Plug 'vifm/vifm.vim'
    " Plug 'scrooloose/nerdtree'
    " Plug 'preservim/nerdtree'
    " Plug 'Xuyuanp/nerdtree-git-plugin'
    " Plug 'tsony-tsonev/nerdtree-git-plugin'
    " Plug 'tiagofumo/vim-nerdtree-syntax-highlight' " Is this required?

**Comment by tjallemaal** [comment]
solved

**Comment by tjallemaal** [comment]
PS: does your `latex setup` conflict with `lunar vim`? I'm eager to install it, too.

**Comment by benbrastmckie** [comment]
Funny you should mention, I'm also interested in LunarVim, and working on a config that is 100% Lua. As it stands, my current config is 100% Vimscript. But stay tuned.
