### ISSUE TITLE
Not printing to Skim automatically

### ISSUE THREAD

**Issue by Vikthor1** [benbrastmckie/.config#83]
Hi Ben,

I fixed the Explorer issue but now Neovim is not printing to Skim. The latex compilation is fine, because when I navigate to the folders I find the pdf with the edits I am working on. But it stopped automatically opening Skim when I run the build command. I ran the diagnostic command and everything seems to be fine. Skim is also properly set as the default pdf reader in the config file. 

Regards and happy new year!

Victor.

**Comment by benbrastmckie** [comment]
Have you tried killing the aux files with `space+k` and deleting the pdf? There is also the .synctex.gz file which is responsible for syncing the pdf. You could delete that file and rebuild. You could also trace back though the installation instructions for MacOS (I assume) and check to see if `skim` has been inserted in the relevant files. See [here](https://github.com/benbrastmckie/.config#skim) for information.

**Comment by benbrastmckie** [comment]
Did you sort this out? If so please include details here in case others run into the same issue.
