### ISSUE TITLE
Which part of the config requires nvim over vim ?

### ISSUE THREAD

**Issue by dlesnoff** [benbrastmckie/.config#84]
I often uses vim in ssh servers to program and I can not install nvim on these servers.
I use a global config for vim for both the servers and my personal machine.
Even though I can install neovim on my personal machine, I would like to know which features require neovim and which can be installed on plain vim.
I would like to congrats for this configuration repository, there has definitely been a lot of involvement for finding the best software.

**Comment by benbrastmckie** [comment]
I have tried to use all lua plugins, so with a few exceptions, most of the plugins will not copy over to Vim. I have maintained the `vimscript` branch in case you want that config instead. It may need to be cleaned up a bit to be perfectly compatible standard Vim. By contrast, the ambition of the master branch is to maximise lua in the config which has the knock-on effect of reducing compatibility with standard Vim. I hope that makes sense.
