### ISSUE TITLE
Sessions don't seem to generate as expected

### ISSUE THREAD

**Issue by JacobMacWilliams** [benbrastmckie/.config#85]
Hi I just pulled down your repo two days ago and configured it on my pc, first of all thanks a million, very cool stuff. Anyways sessions don't seem to be generating as expected, after typing the command \<ctrl\>Ss to save a running session I am not prompted to name the session, and nothing appears on the startify page on the next startup of nvim, which makes sense because nothing new is generated in the session directory either. Is this an issue you have any experience with?

**Comment by JacobMacWilliams** [comment]
Looks like the session directory generated in the wrong folder (.config/session) after  plug.vim ran. Simply moving it to the directory configured in start-screen.vim (.config/nvim/session/) and removing the seemingly superflous kmix files contained within did the trick.

**Comment by benbrastmckie** [comment]
Glad you got it working, and sorry for the no response. I'm only picking back up with issues now unfortunately.
