### ISSUE TITLE
Vimtex section motions not working

### ISSUE THREAD

**Issue by mits-haruko** [benbrastmckie/.config#86]
You should be able to use [[ and ]] to jump back and forth between sections in Vimtex, but somehow I cannot have this to work for me with this config. At first I thought this was a conflict with some of the quick motion plugins but disabling them didn't fix it. Weird enough, jumping between separators with % and environments with [m are still working. I also couldn't find any mapping overwriting this feature. Is this expected?

**Comment by benbrastmckie** [comment]
Sorry for the slow response... If you want to use the Vimtex mappings, go into `vimtex.lua` (or `vimtex.vim` if you are using the Vimscript version of my config), and enable the mappings by setting:
```
vim.g['vimtex_mappings_enabled'] = 0
```
The vimscript command is similar. Does that fix the issue? Note that turning on the mappings may produce other conflicts. This is why I have set custom mappings for the Vimtex commands that I want to use. You can do the same for `[[` and `]]` or whatever else you want to use. Check out the Vimtex help and see the mappings I have included in `whichkey.lua` (or .vim).
