### ISSUE TITLE
nvim plugin startup coc_explorer & more

### ISSUE THREAD

**Issue by chrishudetz** [benbrastmckie/.config#87]
I am running the latest kali linux version on VM workstation pro.

First when starting nvim I get this error here:
![image](https://user-images.githubusercontent.com/41451486/195164977-74a03695-9f85-4c4a-acac-f6e6fb3810f3.png)

Second I get this error here after pressing "Enter" on the previous warning above.

![image](https://user-images.githubusercontent.com/41451486/195165315-28263289-c3aa-455c-9d5d-ef7f260e413f.png)

I am very new to linux and its tools and I am unsure on what could cause this, but I really want to use nvim for notetaking and would love some help!

**Comment by chrishudetz** [comment]
Update, for the first error I just needed to add quote lol should have just read.

**Comment by chrishudetz** [comment]
I can send more screenshots soon, I am running errands at the moment.

**Comment by chrishudetz** [comment]
[image: image.png][image: image.png]

Here are two pictures, one shows the full error (right) and the other shows
the installation of yarn (left)

Thank you so much for your time by the way.

**Comment by benbrastmckie** [comment]
I don't see any images above. I have also ported my config to Lua complete with nvim-lsp etc. in case that is of interest to you. If you are still having trouble, feel free to reopen the issue.

**Comment by chrishudetz** [comment]
Issue has been fixed a lil while ago, love your nvim setup use it all the
time. Thank u!

**Comment by benbrastmckie** [comment]
Glad to hear it!
