### ISSUE TITLE
unable to pull from git repository

### ISSUE THREAD

**Issue by drviveksharma** [benbrastmckie/.config#89]
I am trying to install nvim for the first time . Fedora 37; I wonder if you can help me with the following information.
I get fatal error when trying to pull from the remote repository.
The terminal output is as follows:

you can pm me as well drviveksharma@gmail.com

Thanks
Vivek

⋊> ~/.config on master ⨯ git remote add origin https://github.com/benbrastmckie/                              11:47:32
error: remote origin already exists.
⋊> ~/.config on master ⨯ git remote -v                                                                        11:49:27
origin	https://github.com/benbrastmckie/ (fetch)
origin	https://github.com/benbrastmckie/ (push)
⋊> ~/.config on master ⨯ git pull origin master                                                               11:49:40
remote: Not Found
fatal: repository 'https://github.com/benbrastmckie/' not found
⋊> ~/.config on master ⨯ ls -a                                                                                11:50:21
./                            .git/                          gtk-4.0/       okularrc        texstudio/
../                           gnome-boxes/                   ibus/          omf/            TUG/
abrt/                         gnome-control-center/          libreoffice/   pdfarranger/    user-dirs.dirs
dconf/                        gnome-initial-setup-done       LyX/           procps/         user-dirs.locale
dleyna-renderer-service.conf  gnome-session/                 mimeapps.list  pulse/          xournalpp/
enchant/                      goa-1.0/                       monitors.xml   QtProject.conf  yelp/
evolution/                    google-chrome/                 monitors.xml~  R/              Zettlr/
fish/                         .gsd-keyboard.settings-ported  nautilus/      rstudio/
gh/                           gtk-3.0/                       okularpartrc   RStudio/
⋊> ~/.config on master ⨯

**Comment by benbrastmckie** [comment]
If you are not familiar using Git, I suggest watching some tutorials about how to do some of the basics. It's a little tricky to get used to.

One thing you might do is to try to remove the remote, and then add it back again. I just googled to find this guide:

https://linuxize.com/post/how-to-remove-git-remotes/

I see that your remote address is not correct. It should read like this:
```
 ╰─λ git remote -v
origin  git@github.com:benbrastmckie/.config.git (fetch)
origin  git@github.com:benbrastmckie/.config.git (push)
```
Also, perhaps of interest to you, I've been slowly porting my config to lua. You can find that in the lua branch in my config. I have most of it working the way that I want, though a number of TODOs remain. Once I fix a few more things, I will make another video series going over install, functionality, and customisation. Sorry its been a bit slow... I have a lot going these days, but should be able to make some progress soon.

**Comment by drviveksharma** [comment]
Thanks, I am new to neovim have been using Lyx and Rstudio for most of my writing with Jabref as the bibtex manager. I look forward to seeing the lua branch working as an ide. 
This series is a great help to anyone interested in academic writing, and not get bogged by Word etc. and buying into that ecosystem with added burdens of yearly subscriptions (!) I hope I can get it working as well as your setup.
Look forward to your videos.

**Comment by benbrastmckie** [comment]
Videos are going up: https://www.youtube.com/watch?v=dW9V5wThxCw&feature=youtu.be

I'm still yet to make installation and configuration video series but will soon.

**Comment by drviveksharma** [comment]
Thanks I will watch them
