### ISSUE TITLE
Yanky clipboard error

### ISSUE THREAD

**Issue by dat-le-4** [benbrastmckie/.config#92]
I got this error when open nvim on my mac. 
![](https://user-images.githubusercontent.com/96510793/220671760-f29029e3-fd28-4561-bc5f-d0419b0cc095.png)

If I commented yanky out in plugins.lua and init.lua then its fine. But still haven't found the final solution.

**Comment by benbrastmckie** [comment]
Try changing "unnamedplus" to "unnamed" in `options.lua` and see if [Yanky](https://github.com/gbprod/yanky.nvim) works. If that doesn't work, I'd create an issue on the Yanky repo, mentioning that issue here.

**Comment by dat-le-4** [comment]
That didn't work. Please post a new issue on the Yanky repo. Thanks.

**Comment by benbrastmckie** [comment]
It doesn't make sense for me to post bc I don't have the error, so can't check fixes.

**Comment by dat-le-4** [comment]
I think the problem is I don't have xcel on my mac and I installed it brew install xsel. But now there is a new problem when I ran nvim. 
<img width="610" alt="image" src="https://user-images.githubusercontent.com/96510793/221873166-b840bdf8-c39e-4e01-aa6b-09f8abbea4b5.png">

**Comment by dat-le-4** [comment]
https://github.com/gbprod/yanky.nvim/issues/91#issuecomment-1448274701
This solved the problem.
