### ISSUE TITLE
Snippets don’t work

### ISSUE THREAD

**Issue by 2dope4writingcode** [benbrastmckie/.config#94]
I’ve recently installed your new lua configuration on my macbook. Everything works fine except for the snippets: they don’t show up. Also when I’m deleting something an error appears saying “xsel”.. idk how to solve those two problems. Thank you for the answer in case.

**Comment by benbrastmckie** [comment]
So just to clarify... if you type `enum` in neovim, do you get any autocompletion at all? Can you include a screenshot?

As for the `xsel` error, do you have `xsel` installed? If you run `:which xsel` what comes up? A screenshot of that error could also help.

**Comment by benbrastmckie** [comment]
For the `xsel` error, you might try removing the `vim.g.clipboard` block from `options.lua`.

**Comment by 2dope4writingcode** [comment]
Thank you! For the xsel worked. But idk why the snippets don’t show up. The path in luasnip.lua it’s correct for the snippets.tex

**Comment by 2dope4writingcode** [comment]
> 

I have all the other autocompletitions except for the snippets

**Comment by 2dope4writingcode** [comment]
![Uploading 815D0D2E-0FFD-46BC-AC1D-BF5E8815D29E.jpeg…]()

**Comment by 2dope4writingcode** [comment]
![CFCB1E56-D28F-4429-90F7-9AFCB862C7DB](https://user-images.githubusercontent.com/117725672/224288284-357b9e66-ae97-4a1a-8baa-06aedb83bb2f.jpeg)

**Comment by 2dope4writingcode** [comment]
![445F067B-8318-4DD1-A4B7-184336310CCB](https://user-images.githubusercontent.com/117725672/224288430-3e98ec9d-ace7-4460-845f-8dcaee72d9e6.jpeg)

**Comment by 2dope4writingcode** [comment]
yes I have them.

**Comment by benbrastmckie** [comment]
Hum it's not clear to me what's going wrong. You might try searching through the open and closed issues for luasnip to see if you can find something similar and opening an issue there if you can't find anything. So far there aren't a lot of clues to what is going wrong.





'''
:LuaSnipListAvailable

**Comment by 2dope4writingcode** [comment]
![0A31EB2E-6524-4030-9E67-235DDFAA172F](https://user-images.githubusercontent.com/117725672/224488705-6165463f-5a7c-48ef-b69d-5ef9326fddb3.jpeg)

that’s the result when I’m entering :LuasnipListAvailable

**Comment by benbrastmckie** [comment]
Ok so at least the plugin seems to be working. It just can't access your snippets. I would open an issue on [luasnip](https://github.com/L3MON4D3/LuaSnip/issues) to see if someone who is more knowledgeable about the plugin can help you. I know you said that you already checked that the path was correct, but you might double check by going into `luasnip.lua` and hover the cursor over the path and hit `gf` for go-to-file. You will then have to open the file in the directory that opens to check to see that the snippets are all there. Whatever it is, I imagine it won't take much to fix once you figure out what's getting in the way.

**Comment by 2dope4writingcode** [comment]
Thank you. I opened the file path as you said and the snippets were all there. The problem was that sometimes luasnip can stop working so I need to reinstall it w packer again. Now is working fine.
