### ISSUE TITLE
Clipboard not functional on Kali linux 2023.1

### ISSUE THREAD

**Issue by Gurmukh-Singh-4253** [benbrastmckie/.config#95]
machine="aarch64"
release="6.1.0-kali5-arm64"
sysname="Linux"
version="#1 SMP Debian 6.1.12-1kali2 (2023-02-23)"

I followed all installation functions from the macOS column (it is the only updated one at the moment) after appropriately translating and modifying the commands. Everything else is functional, but whenever I try to yank or delete something, i get this error (see picture below) saying xsel is not executable.

<img width="1440" alt="Screenshot 2023-03-27 at 07 17 58" src="https://user-images.githubusercontent.com/111715777/227821609-8522d7b8-b8b8-4833-9b3c-26b2b9e93ebb.png">

**Comment by benbrastmckie** [comment]
I will update the Linux installation soon, but have you tried installing xsel? If so, or if that doesn't fix it, try removing the last block in the options.lua file which calls xsel. Let me know if that helps.

**Comment by Gurmukh-Singh-4253** [comment]
Yes sir, resolved.
