### ISSUE TITLE
Installation issues in Ubuntu

### ISSUE THREAD

**Issue by rafisics** [benbrastmckie/.config#97]
The following two commands in [Debian Linux Installation](https://github.com/benbrastmckie/.config#debian-linux-installation) don't work in Ubuntu 22.04 LTS:
```
sudo apt install lazygit
```

```
sudo apt install alacritty
```

**Comment by benbrastmckie** [comment]
Thanks for the catch. I just looked it up and cut and paste the instructions I found. Let me know if you have any further trouble with those steps, and if the instructions there are sufficient.

**Comment by rafisics** [comment]
I have followed the steps mentioned [here](https://github.com/benbrastmckie/.config#alacritty-tmux-and-fish-optional-1).
But when I reopen Alacritty, Fish doesn't appear be the default shell inside a Tmux window.

**Comment by rafisics** [comment]
Another issue is, each time I run `nvim` in the terminal, it shows:
```
Error detected while processing /home/rafi/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/rafi/.config/nvim/lua/user/keymaps.l
ua:33: attempt to index field 'keymap' (a nil value)
stack traceback:
        /home/rafi/.config/nvim/lua/user/keymaps.lua:33: in main chunk
        [C]: in function 'require'
        /home/rafi/.config/nvim/init.lua:3: in main chunk
Press ENTER or type command to continue
```

**Comment by benbrastmckie** [comment]
I'm not sure from your description what the problem with Fish is. Did it fix it after closing Alacritty? You can also run `tmux kill-server` and reopen Alacritty to check to see if Fish is set by default.

As for the error, it is pointing you to line 33 in the `keymaps.lua` file. You should check out what is going on at that line. Whatever keybinding it provides, you can run `:verbose map KEYBINDING` to see what that keybinding is doing, and if it is being set in conflicting ways at different places. Feel free to cut and paste what you find.

**Comment by msaeedk** [comment]
I too have similar issues mentioned above. If your time permits could you please make an installation video for debian based systems.  I am newb :).

**Comment by msaeedk** [comment]
After trying as per in ReadMe file. I tried to do remapping of keys first, because it shows error there when i checked health in neovim. But ubuntu doesn't have xorg-keymap  in repository.

**Comment by msaeedk** [comment]
This keymap issue won't be there if you install a newer version of neovim. Neovim is so old in debian repository. I built the latest version and it is gone. But now I have another issue.        
Error detected while processing /home/saeed/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/saeed/.config/nvim/lua/user/surround
.lua:1: module 'nvim-surround' not found:
        no field package.preload['nvim-surround']
        no file './nvim-surround.lua'
        no file '/home/saeed/neovim/.deps/usr/share/luajit-2.1.0-beta3/nvim-surr
ound.lua'
        no file '/usr/local/share/lua/5.1/nvim-surround.lua'
        no file '/usr/local/share/lua/5.1/nvim-surround/init.lua'
        no file '/home/saeed/neovim/.deps/usr/share/lua/5.1/nvim-surround.lua'
        no file '/home/saeed/neovim/.deps/usr/share/lua/5.1/nvim-surround/init.l
ua'
        no file './nvim-surround.so'
        no file '/usr/local/lib/lua/5.1/nvim-surround.so'
        no file '/home/saeed/neovim/.deps/usr/lib/lua/5.1/nvim-surround.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/saeed/.config/nvim/lua/user/surround.lua:1: in main chunk
        [C]: in function 'require'
        /home/saeed/.config/nvim/init.lua:13: in main chunk

Any suggestions?.

**Comment by benbrastmckie** [comment]
Is it crashing NeoVim entirely? That is, are you able to get into NeoVim without it reverting to vanilla NeoVim? If so, it looks like [nvim-surround](https://github.com/kylechui/nvim-surround) is the issue. You might try checking the `plugins.lua` file to make sure `nvim-surround` is being used, and also try running `:PackerInstall` in case it didn't get installed.

Also worth trying running a surround command by visually selecting some text and hitting `<S-s>$` to see if it will wrap that text with '$'s.

You can also try turning off `nvim-surround` by commenting out the relevant lines in `plugins.lua` and `init.lua`, i.e., lines that use the plugin and require the config file. If that gets rid of the error, then the next step would be see if anyone has gotten similar errors in the issues on the `nvim-surround` repo. If so, please link those issues here for others to follow.

Feel free to post what you find along the way here.

**Comment by msaeedk** [comment]
I guess it is not issue from your end. I had a nodejs which was version 12 only (debian packages are far slow compared to arch, that is why you don't have issues). I slowly healthchecked  commenting out your init.lua. Now it is almost working. If everything goes alright. I shall add the relevant links here inshallah.

**Comment by msaeedk** [comment]
@benbrastmckie , Thanks a lot man for this nice configuration. All issues are resolved  for me now.  Please check if "help".. is essential in the file treesitter.lua  in the function configs.setup(). It was giving an error parser not available for language "help". I commented  it . 

- The key map error shown by   @rafisics  can be resolved by updating Neovim to the latest version. Don't use $ sudo apt install neovim  .    You have to install latest Neovim from source. 
- Also check version of node by $ node  --version. It will create issue if it is 12 or around. You should build node and remove the existing node package by $ sudo apt purge node.
- In every step try to :checkhealth in Neovim. It will give clues on where the errors  originate . 
- This issue in [Treesitter](https://github.com/nvim-treesitter/nvim-treesitter/issues/3092) may also occur.

**Comment by benbrastmckie** [comment]
That's great. I've tried to add these points to the ReadMe, but if you care to edit it making any changes you feel are relevant, I'd be happy to accept a PR. Happy Vimming!

**Comment by rafisics** [comment]
On a different Ubuntu 22.04 LTS machine, I have followed the steps up to the section [Debian Linux Installation (Dependencies)](https://github.com/benbrastmckie/.config#dependencies-2) so far.
I am facing the following issues while running `nvim` in terminal:
```
Error detected while processing /home/rafi/.config/nvim/init.lua:
E5248: Invalid character in group name
Installation not possible: ...er/start/nvim-treesitter/lua/nvim-treesitter/insta
ll.lua:86: Parser not available for language "help"
See https://github.com/nvim-treesitter/nvim-treesitter/#adding-parsers on how to
 add a new parser!
```
```
view.mappings.list has been deprecated in favour of on_attach. Please run :NvimT
reeGenerateOnAttach and visit https://github.com/nvim-tree/nvim-tree.lua/wiki/Mi
grating-To-on_attach
```

**Comment by Redyf** [comment]
> On a different Ubuntu 22.04 LTS machine, I have followed the steps up to the section [Debian Linux Installation (Configuration)](https://github.com/benbrastmckie/.config#configuration-2) so far. I am facing the following issues while running `nvim` in terminal:
> 
> ```
> Error detected while processing /home/rafi/.config/nvim/init.lua:
> E5248: Invalid character in group name
> Installation not possible: ...er/start/nvim-treesitter/lua/nvim-treesitter/insta
> ll.lua:86: Parser not available for language "help"
> See https://github.com/nvim-treesitter/nvim-treesitter/#adding-parsers on how to
>  add a new parser!
> ```
> 
> ```
> view.mappings.list has been deprecated in favour of on_attach. Please run :NvimT
> reeGenerateOnAttach and visit https://github.com/nvim-tree/nvim-tree.lua/wiki/Mi
> grating-To-on_attach
> ```

Go to .config/nvim/lua/user/treesitter.lua and comment "help".

```lua
local status_ok, configs = pcall(require, "nvim-treesitter.configs")
if not status_ok then
    return
end

configs.setup({
  ensure_installed = {  -- list "all" or a list of languages
    "markdown_inline", 
    "markdown", 
    "lua", 
    "python", 
    "vim", 
    "yaml", 
    "perl", 
    "json", 
    "html", 
    --"help", 
    "haskell", 
    "gitignore", 
    "bibtex" 
  },
    ignore_install = { "latex" }, -- List of parsers to ignore installing
    highlight = {
        enable = true, -- false will disable the whole extension
        disable = { "css", "latex" }, -- list of language that will be disabled
    -- additional_vim_regex_highlighting = { "latex", "markdown" },
    },
    autopairs = {
        enable = true,
    },
    indent = { enable = true, disable = { "latex", "python", "css" } },
})
```

**Comment by Redyf** [comment]
> On a different Ubuntu 22.04 LTS machine, I have followed the steps up to the section [Debian Linux Installation (Configuration)](https://github.com/benbrastmckie/.config#configuration-2) so far. I am facing the following issues while running `nvim` in terminal:
> 
> ```
> Error detected while processing /home/rafi/.config/nvim/init.lua:
> E5248: Invalid character in group name
> Installation not possible: ...er/start/nvim-treesitter/lua/nvim-treesitter/insta
> ll.lua:86: Parser not available for language "help"
> See https://github.com/nvim-treesitter/nvim-treesitter/#adding-parsers on how to
>  add a new parser!
> ```
> 
> ```
> view.mappings.list has been deprecated in favour of on_attach. Please run :NvimT
> reeGenerateOnAttach and visit https://github.com/nvim-tree/nvim-tree.lua/wiki/Mi
> grating-To-on_attach
> ```

For the view.mappings.list error, it's deprecated so you need to migrate to the latest one which is (on_attach).
Follow the guide in: https://github.com/nvim-tree/nvim-tree.lua/wiki/Migrating-To-on_attach#example

**Comment by benbrastmckie** [comment]
Thanks for these, and sorry for my absence. I've updated `treesitter.lua` to remove `help` and updated `nvim-tree.lua` to include `on_attach`.

**Comment by rafisics** [comment]
Thank you for the help, @benbrastmckie and @Redyf.

**Comment by rafisics** [comment]
Another issue is regarding `autolist.nvim`. It shows:
```
autolist.nvim: There has been a major update Please read the README again for guide. 
```

**Comment by benbrastmckie** [comment]
Yes saw that error two and fixed it. You can either follow the directions on the autolist GitHub, or check out my updated autolist.lua file and plugins.lua file. There's also a nice function I added to the autolist.lua file for checking boxes. See my whichkey.lua file for the key binding.

**Comment by rafisics** [comment]
I just `git pull`-ed the update of this repository in my Ubuntu Linux machine. I am facing some issues. 
Calling `fish` on my terminal is showing now:
```
warning: An error occurred while redirecting file '/home/rafi/.config/fish/config.fish'
open: No such file or directory
```
Why is it happening?

**Comment by benbrastmckie** [comment]
My apologies, and thanks for the heads up. The problem was caused by the way I'm managing my dot files, and it is clashing with the config. I put everything back, so should work now without issue (if you pull again). Let me know if you have any further trouble.

The issue is that it was following the symlink that my dot file management system in nixos created in place of the fish config file, and there is no fish config file in the place it was pointing on your system. But now the file is back in place so should work.

Hope that helps!

**Comment by rafisics** [comment]
Thank you. That issue is solved now. 
But, now, when I call `nvim`, it appears like this:
![image](https://github.com/benbrastmckie/.config/assets/68302816/221670a3-d90d-4192-a6a2-ead8f83fde89)

**Comment by rafisics** [comment]
Also, now, compiling my tex file is not opening the pdf file.

**Comment by benbrastmckie** [comment]
If you go into `Config` by hitting `c`, and then open `mason.lua` by hitting `ctrl-p` and typing 'Mason.lua', you can comment out the lines with `pylint` and `isort` assuming you aren't using python. Try reloading to see if the errors go away. Better yet, if you don't care about having formatting and linting at all, you can go into `nvim-tree` with `space+e` and the file for `Mason.lua` should be highlighted assuming it is open. You can then cut this file with `x` and paste it into the `../depreciated/` directory by navigating to it, opening it with `l` and pasting with `p` (you shouldn't need to modify the require path). Then upon reload, you shouldn't have any linter or formatting errors. 

As for the icons, go into the `alpha.lua` file in your config by a similar procedure, and see what icons are not loading. You can search for icons to replace them [here](https://www.nerdfonts.com/cheat-sheet). Find something you like that works, and then you should be good to go.

As for compiling latex files, try running `:checkhealth` (also accessible from the start menu) and see if VimTex is happy. 

Hope that helps!

**Comment by rafisics** [comment]
Ok. It seems there are some issues. Going to `Config` shows this:
![image](https://github.com/benbrastmckie/.config/assets/68302816/5cdccdcb-2ad0-427b-8dc5-5addd5ef38f9)
Pressing `Enter`:
![image](https://github.com/benbrastmckie/.config/assets/68302816/62c6c2b4-d964-40c8-83e3-3c01420dbe73)
Everything is properly functioning before the recent changes. I think the setup instructions for Linux should be updated.

**Comment by benbrastmckie** [comment]
I think you just need to remove that 'mason.lua' file. The errors are just letting you know that it can't find the right linters. This doesn't affect you at all, we just need the warnings to turn off.

It shouldn't be hard to fix. 

The latex error is more troubling. Is that still not working?

**Comment by benbrastmckie** [comment]
I took another look at this and updated the `mason.lua` file to only load in appropriate filetypes. So if you never open python, then there is nothing to worry about. I also updated the README to include the packages:

```
sudo apt install stylua
sudo apt install lua-language-server
```

That way you will have a formatting available for lua which is what the config is written in. Let me know if that helps, and if you run into any further problems.

**Comment by rafisics** [comment]
`:checkhealth` shows this now:
![image](https://github.com/benbrastmckie/.config/assets/68302816/f6818787-6814-4610-abd3-97645c161958)


> So if you never open python, then there is nothing to worry about.

Now, I do python coding in VS Code, but I was writing LaTeX with the nvim config of urs. 

> As for the icons, go into the `alpha.lua` file in your config by a similar procedure, and see what icons are not loading.

I am confused, I couldn't find the `alpha.lua` file!

**Comment by benbrastmckie** [comment]
Sorry for all the troubles. Pulling updates can definitely break things but I hope that switching to the new config is worth it. I've found lazy.nvim package manager much better to work with than packer.

If you are using python that's a good reason to get the linters working unless you don't like linters or are happy in VSCode. I personally love being able to do everything in one place. However, if you don't want to use python in neovim then there is nothing to do (though it will probably give you errors if you open a python file). So far as I can tell, the python errors coming from `pylint` and `isort` have been resolved.

The lua linter/formater is still not happy though. You are right that `apt get` doesn't have the packages you need. It looks like it installs through npm though which is already a dependency of the config. So you can try running:

```
npm i @johnnymorganz/stylua
npm i @salesforce/lwc-language-server
```

I don't have a debian machine to try this out on, but let me know if you run into trouble.

For the sessions problem, I'm thinking that you may have to clear out your `~/.local/share/nvim` directory. This is good to do anyways given the update. This will wipe the slate clean so that neovim will put new auxiliary files in place on the next time you run it. To do this, you can run the following from the terminal:

```
rm -rf ~/.local/share/nvim
```

Try reopening neovim and see if you get the same sessions errors. I'm hoping that this fixes the checkhealth problems as well.

If you still get the sessions error, you might try creating a new session. For instance, you might: 1) go into your config from the home screen with `c`; update the working directory with `space+a+u` (that way the file tree will only include relevant directories); and save session with `space+S+s`. Then try exiting and reopening neovim.

**Comment by rafisics** [comment]
Firstly, thank you for your continuous support. 
Running `npm i @salesforce/lwc-language-server` gives me this issue:
```
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.

added 249 packages, and audited 520 packages in 43s

91 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (2 moderate, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```
Then from `npm audit fix` gives:
```
npm WARN audit fix ip@2.0.0 node_modules/npm/node_modules/ip
npm WARN audit fix ip@2.0.0 is a bundled dependency of
npm WARN audit fix ip@2.0.0 npm@10.1.0 at node_modules/npm
npm WARN audit fix ip@2.0.0 It cannot be fixed automatically.
npm WARN audit fix ip@2.0.0 Check for updates to the npm package.

up to date, audited 520 packages in 3s

91 packages are looking for funding
  run `npm fund` for details

# npm audit report

@babel/traverse  <7.23.2
Severity: critical
Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code - https://github.com/advisories/GHSA-67hx-6x53-jw92
No fix available
node_modules/@lwc/metadata/node_modules/@babel/traverse
  @lwc/metadata  <=3.7.0-0
  Depends on vulnerable versions of @babel/traverse
  node_modules/@lwc/metadata
    @salesforce/lwc-language-server  *
    Depends on vulnerable versions of @lwc/metadata
    Depends on vulnerable versions of xml2js
    node_modules/@salesforce/lwc-language-server

ip  2.0.0
Severity: moderate
NPM IP package incorrectly identifies some private IP addresses as public - https://github.com/advisories/GHSA-78xj-cgh5-2h22
fix available via `npm audit fix`
node_modules/npm/node_modules/ip

xml2js  <0.5.0
Severity: moderate
xml2js is vulnerable to prototype pollution - https://github.com/advisories/GHSA-776f-qx25-q3cc
No fix available
node_modules/xml2js

5 vulnerabilities (2 moderate, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.
```
And I have cleared `~/.local/share/nvim` directory.
But the issues are not resolved yet. 
When I go to Config with `c`, it shows:
```                                                            
[null-ls] failed to load builtin eslint_d for method diagnostics; please check your config                                                        
Spawning language server with cmd: `lua-language-server` failed. The language server is
 either not installed, missing from PATH, or not executable 
 Press ENTER or type a command to continue
 ```
 Pressing `ENTER`, it shows `init.lua` with these errors:
![image](https://github.com/benbrastmckie/.config/assets/68302816/fea559a9-387a-42b0-bed3-c01e98d3f287)

**Comment by benbrastmckie** [comment]
What happens if you run the following commands (separately):
```
which stylua
which lua-language-server
```
If these are installed, then you should be good.

Regarding the new error above, what happens if you run `:Mason` and hit `U` for update? I have also just removed `eslint_d` in case the first idea doesn't help (you will have to pull again).

**Comment by rafisics** [comment]
Weirdly `which stylua` and `which lua-language-server` aren't showing anything.

**Comment by benbrastmckie** [comment]
I just looked at your config and it seems you removed `Mason.lua`. That's fine if you don't want linters for python etc. That also means that you shouldn't worry about `stylua` etc. Instead, you need to also remove `none-ls.lua`. This will make your config diverge from mine (so manybe annoying if you want to pull in the future) and remove all linting.

The other way to go is to add `mason.lua` back where it was and fix all the issues with the linters. For instance, you can try `npm audit fix` to try to finish the installation. This might be nice if you want to use neovim for python.

Whichever way you go, I would suggest keeping a depreciated directory so that you can easily cut pieces out of your config without completely removing them. Note that the depreciated directory I have does not get sourced and so those files are essentially backups. I use them for plugins I tried but didn't like, or don't want to use right now, but it is also useful when fussing with the config itself.

**Comment by rafisics** [comment]
> The other way to go is to add `mason.lua` back where it was and fix all the issues with the linters. For instance, you can try `npm audit fix` to try to finish the installation. This might be nice if you want to use neovim for python.

I would like to do this.

**Comment by benbrastmckie** [comment]
Ok great! Happy to help along the way. Shouldn't be too hard honestly. Doing another pull should put `mason.lua` back where it was.

**Comment by rafisics** [comment]
I am not, it's already up to date. 
```
From https://github.com/benbrastmckie/.config
 * branch            master     -> FETCH_HEAD
Already up to date.
```
And `npm audit fix` gives this same result as I showed [before](https://github.com/benbrastmckie/.config/issues/97#issuecomment-1979069424):
```
npm WARN audit fix ip@2.0.0 node_modules/npm/node_modules/ip
npm WARN audit fix ip@2.0.0 is a bundled dependency of
npm WARN audit fix ip@2.0.0 npm@10.1.0 at node_modules/npm
npm WARN audit fix ip@2.0.0 It cannot be fixed automatically.
npm WARN audit fix ip@2.0.0 Check for updates to the npm package.

up to date, audited 520 packages in 4s

91 packages are looking for funding
  run `npm fund` for details

# npm audit report

@babel/traverse  <7.23.2
Severity: critical
Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code - https://github.com/advisories/GHSA-67hx-6x53-jw92
No fix available
node_modules/@lwc/metadata/node_modules/@babel/traverse
  @lwc/metadata  <=3.7.0-0
  Depends on vulnerable versions of @babel/traverse
  node_modules/@lwc/metadata
    @salesforce/lwc-language-server  *
    Depends on vulnerable versions of @lwc/metadata
    Depends on vulnerable versions of xml2js
    node_modules/@salesforce/lwc-language-server

ip  2.0.0
Severity: moderate
NPM IP package incorrectly identifies some private IP addresses as public - https://github.com/advisories/GHSA-78xj-cgh5-2h22
fix available via `npm audit fix`
node_modules/npm/node_modules/ip

xml2js  <0.5.0
Severity: moderate
xml2js is vulnerable to prototype pollution - https://github.com/advisories/GHSA-776f-qx25-q3cc
No fix available
node_modules/xml2js

5 vulnerabilities (2 moderate, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.
```

**Comment by benbrastmckie** [comment]
It looks like you do have a mason file still: 

https://github.com/rafisics/.config/blob/master/nvim/lua/user/lsp/mason.lua

But it is different than the one I have. What may be going on is that I had assumed you pulled from upstream. Is that true? If you haven't done this, note that doing so will cause many changes to your config. You can check your remotes with:

```
git remove -v
```
Alternatively, you can cut and paste pieces testing each. This is tedious but safe. Or you can try pulling from upstream, see if it work, and if it doesn't revert to your last commit. Not sure what you prefer, but those are some options.

**Comment by rafisics** [comment]
Sorry for the confusion. I am not using the forked one ([https://github.com/rafisics/.config](https://github.com/rafisics/.config/blob/master/nvim/lua/user/lsp/mason.lua)) right now. 
![image](https://github.com/benbrastmckie/.config/assets/68302816/2671d65d-1cf5-4eb5-a0b9-d3b2366c5b0d)

**Comment by benbrastmckie** [comment]
Is the `mason.lua` file in place? It should be. Maybe you never removed it?

Since you are going through the trouble it might be worth working off of a fork. This will give you the ability to diverge and cherry pick future changes that I make in the future. But no worries if you want to pull the main config.

Seems like the next main issue is to chase down all the errors. Is sessions working? Installing stylua, pylint, etc may take some googling. But shouldn't be too hard.

**Comment by benbrastmckie** [comment]
That sounds about right. It will probable take a bit to troubleshoot but hopefully not too much.

**Comment by rafisics** [comment]
I've just done:
```
rm -rf ~/.local/share/nvim
```
Reopening the `nvim` shows: 
![Screenshot from 2024-03-30 12-58-30](https://github.com/benbrastmckie/.config/assets/68302816/1aa4079c-9062-4914-a9aa-d55abcdc16e1)

Currently, `:checkhealth` is like: 
```

==============================================================================
dressing: require("dressing.health").check()

dressing.nvim ~
- OK vim.ui.input active
- OK vim.ui.select active: telescope

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found
- WARNING {autolist.nvim}: unknown key <filetype>

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /usr/local/share/nvim/runtime

Performance ~
- OK Build type: RelWithDebInfo

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $VTE_VERSION="6800"
- $COLORTERM="truecolor"

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.12.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.5.0-26-generic",
  sysname = "Linux",
  version = "#26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider: require("provider.health").check()

Clipboard (optional) ~
- OK Clipboard tool found: xsel

Python 3 provider (optional) ~
- `g:python3_host_prog` is not set.  Searching for python3 in the environment.
- Executable: /usr/bin/python3
- Python version: 3.10.12
- pynvim version: 0.4.3
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

Node.js provider (optional) ~
- Node.js: v20.12.0
- Nvim node.js host: /usr/lib/node_modules/neovim/bin/cli.js

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.3.1

===== Installed extensions ===== ~

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /home/rafi/.local/state/nvim/lsp.log
- Log size: 0 KB

vim.lsp: Active Clients ~
- No active clients

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: bash       ABI: 14, path: /home/rafi/.local/share/nvim/lazy/nvim-treesitter/parser/bash.so
- OK Parser: bibtex     ABI: 13, path: /home/rafi/.local/share/nvim/lazy/nvim-treesitter/parser/bibtex.so
- OK Parser: c          ABI: 14, path: /home/rafi/.local/share/nvim/lazy/nvim-treesitter/parser/c.so
- OK Parser: gitignore  ABI: 13, path: /home/rafi/.local/share/nvim/lazy/nvim-treesitter/parser/gitignore.so
- OK Parser: haskell    ABI: 14, path: /home/rafi/.local/share/nvim/lazy/nvim-treesitter/parser/haskell.so
- OK Parser: html       ABI: 14, path: /home/rafi/.local/share/nvim/lazy/nvim-treesitter/parser/html.so
- OK Parser: json       ABI: 14, path: /home/rafi/.local/share/nvim/lazy/nvim-treesitter/parser/json.so
- OK Parser: lua        ABI: 14, path: /home/rafi/.local/share/nvim/lazy/nvim-treesitter/parser/lua.so
- OK Parser: norg       ABI: 14, path: /home/rafi/.local/share/nvim/lazy/nvim-treesitter/parser/norg.so
- OK Parser: python     ABI: 14, path: /home/rafi/.local/share/nvim/lazy/nvim-treesitter/parser/python.so
- OK Parser: query      ABI: 14, path: /home/rafi/.local/share/nvim/lazy/nvim-treesitter/parser/query.so
- OK Parser: vim        ABI: 14, path: /home/rafi/.local/share/nvim/lazy/nvim-treesitter/parser/vim.so
- OK Parser: vimdoc     ABI: 14, path: /home/rafi/.local/share/nvim/lazy/nvim-treesitter/parser/vimdoc.so
- OK Parser: yaml       ABI: 14, path: /home/rafi/.local/share/nvim/lazy/nvim-treesitter/parser/yaml.so
- OK Parser: c          ABI: 14, path: /usr/local/lib/nvim/parser/c.so
- OK Parser: lua        ABI: 14, path: /usr/local/lib/nvim/parser/lua.so
- OK Parser: query      ABI: 14, path: /usr/local/lib/nvim/parser/query.so
- OK Parser: vim        ABI: 14, path: /usr/local/lib/nvim/parser/vim.so
- OK Parser: vimdoc     ABI: 14, path: /usr/local/lib/nvim/parser/vimdoc.so

==============================================================================
vimtex: health#vimtex#check

VimTeX ~
- OK Vim version should have full support!
- OK Zathura should work properly!
- OK Compiler should work!

==============================================================================
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- OK No conflicting keymaps found

```

**Comment by rafisics** [comment]
The PDF file is still opening after VimTeX compilation.

**Comment by rafisics** [comment]
I have mentioned my PDF viewer issue with Zathura here: https://github.com/lervag/vimtex/issues/1806#issuecomment-2027994939

**Comment by rafisics** [comment]
I just figured VimTeX couldn't open the PDF through Zathura is because my working directory name has a colon (:) symbol. 

For example, if the PDF file `main.pdf` is in the directory `~/Documents/testing test`, I can open it:
```
zathura '~/Documents/testing test/main.pdf'
```
But my folder name was `testing: test` and in that case, it wasn't opening with zathura:
```
zathura '~/Documents/testing: test/main.pdf'
```
Is there any way to fix it? Or is it recommended not to put a colon in the folder or directory names?

**Comment by benbrastmckie** [comment]
I would definitely avoid colons, spaces, or other strange symbols in directory names. Underscores are best.

Sorry for the long delay!
